# Generated by Django 5.0.6 on 2026-04-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_invitecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitnote",
            name="expansion_adding_equipment",
            field=models.BooleanField(default=False, verbose_name="Adding equipment"),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="expansion_adding_sq_footage",
            field=models.BooleanField(
                default=False, verbose_name="Adding square footage"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="expansion_capex_planned",
            field=models.BooleanField(
                default=False, verbose_name="Capital expenditure planned"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="expansion_new_building",
            field=models.BooleanField(
                default=False, verbose_name="Looking for / moving to new building"
            ),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="expansion_notes",
            field=models.TextField(blank=True, verbose_name="Expansion details"),
        ),
        migrations.AddField(
            model_name="visitnote",
            name="received_business_lead",
            field=models.BooleanField(
                default=False, verbose_name="Received a business lead or referral"
            ),
        ),
    ]
