# Generated by Django 5.0.6 on 2026-05-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_message_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_inactivity_notified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
