# Generated by Django 5.2.13 on 2026-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_status_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_inactivity_reminded",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
