# Generated by Django 5.2.13 on 2026-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_add_last_inactivity_reminded"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sms_reminders_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
