# Generated by Django 5.2.13 on 2026-06-11 20:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_merge_migration_branches"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["name"],
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelManagers(
            name="company",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
